version: '3.9'

services:
  postgres-users:
    image: postgres:17
    container_name: postgresql-monorepo-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - '5441:5432'
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d users']
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  postgres_data_test:
