name: Gate Service â€“ Docker Compose + KIND

on:
  pull_request:
    # types: [closed]
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: .env2

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Setup Docker
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      # 4) Install KIND
      - name: Install KIND
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

      # 5) Create KIND cluster
      - name: Create KIND cluster
        run: |
          kind create cluster --name monorepo --config kind-config.yaml

      # 6) Build gate image using Docker Compose
      - name: Build gate image
        run: |
          SERVICE=${{ secrets.GATE_SERVICE }} docker compose build gate

      - name: Build users image
        run: |
          SERVICE=${{ secrets.USERS_SERVICE }}  docker compose build users

      # 7) Load image into KIND
      - name: Load image into KIND
        run: |
          kind load docker-image gate-service:ci --name monorepo
          kind load docker-image users-service:ci --name monorepo

      - name: Apply secrets
        run: |
          kubectl create secret generic users \
            --from-literal=NODE_ENV=${{ secrets.NODE_ENV }} \
            --from-literal=PG_URL=${{ secrets.PG_URL }} \
            --from-literal=PORT=${{ secrets.PORT }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # 8) Deploy to Kubernetes
      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/gate 
          kubectl apply -f k8s/users

      # 9) Wait for rollout
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/gate --timeout=120s

      # 10) Debug info
      - name: Get pods
        run: |
          kubectl get pods -o wide

      - name: Port forward gate
        run: |
          kubectl port-forward svc/gate 3000:3000 &
          sleep 2

      - name: Test API
        run: |
          curl -v http://localhost:3000/api/v1/users

      - name: Logs on failure
        if: failure()
        run: |
          kubectl logs -l app=gate
